services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: pizza-backend:1.0
    ports:
      - "${PORT}:3001"
    environment:
      DB_HOST: "${DB_HOST}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      JWT_SECRET: "${JWT_SECRET}"

 
