name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: docker build -t pizza-backend:latest .

    - name: Push Docker image to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
      run: |
        echo "$SSH_PRIVATE_KEY" > ~/ec2-svapikey.pem
        chmod 600 ~/ec2-svapikey.pem
        scp -i ~/ec2-svapikey.pem docker-compose.yml ubuntu@<EC2_PUBLIC_IP>:/home/ubuntu/pizza-backend
        ssh -i ~/ec2-svapikey.pem ubuntu@<EC2_PUBLIC_IP> << 'EOF'
          cd /home/ubuntu/pizza-backend
          docker-compose down
          docker-compose up -d --build
        EOF
